name: test-petstore
target_url: https://petstore.swagger.io
created_at: '2026-01-12T12:38:30.407573'
endpoints:
- url: https://petstore.swagger.io
  path: ''
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://petstore.swagger.io/gtm.js
  path: /gtm.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://petstore.swagger.io/swagger-initializer.js
  path: /swagger-initializer.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://petstore.swagger.io/audio/
  path: /audio/
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://petstore.swagger.io/path/index.html
  path: /path/index.html
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://petstore.swagger.io/?
  path: /
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://petstore.swagger.io/image/
  path: /image/
  method: GET
  query: ''
  tags:
  - file-handling
  type: page
- url: https://petstore.swagger.io/video/
  path: /video/
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://petstore.swagger.io/oauth2-redirect.html
  path: /oauth2-redirect.html
  method: GET
  query: ''
  tags:
  - general
  type: auth
- url: https://petstore.swagger.io/s.json%7C%7CRr.call%28i,u%29%7C%7C%21Rr.call%28o,u%29%7C%7C%28s.line=w%7C%7Cs.line,s.lineStart=x%7C%7Cs.lineStart,s.position=C%7C%7Cs.position,throwError%28s,
  path: /s.json%7C%7CRr.call%28i,u%29%7C%7C%21Rr.call%28o,u%29%7C%7C%28s.line=w%7C%7Cs.line,s.lineStart=x%7C%7Cs.lineStart,s.position=C%7C%7Cs.position,throwError%28s,
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://petstore.swagger.io/multipart/
  path: /multipart/
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://petstore.swagger.io/'+escapeHtml(s[o].href)+'
  path: /'+escapeHtml(s[o].href)+'
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://petstore.swagger.io/t.json%7C%7Cqt.call%28r,o%29%7C%7C%21qt.call%28e,o%29%7C%7C%28t.line=a%7C%7Ct.line,t.lineStart=s%7C%7Ct.lineStart,t.position=u%7C%7Ct.position,throwError%28t,
  path: /t.json%7C%7Cqt.call%28r,o%29%7C%7C%21qt.call%28e,o%29%7C%7C%28t.line=a%7C%7Ct.line,t.lineStart=s%7C%7Ct.lineStart,t.position=u%7C%7Ct.position,throwError%28t,
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://petstore.swagger.io/oauth2-redirect.js
  path: /oauth2-redirect.js
  method: GET
  query: ''
  tags:
  - general
  type: auth
- url: https://petstore.swagger.io/swagger-ui-bundle.js
  path: /swagger-ui-bundle.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://petstore.swagger.io/v2/swagger.json
  path: /v2/swagger.json
  method: GET
  query: ''
  tags:
  - api
  type: page
- url: https://converter.swagger.io/api/openapi.json
  path: /api/openapi.json
  method: GET
  query: ''
  tags:
  - api
  type: api
- url: https://validator.swagger.io/validator/openapi.json
  path: /validator/openapi.json
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://generator.swagger.io/api/swagger.json
  path: /api/swagger.json
  method: GET
  query: ''
  tags:
  - api
  type: api
- url: https://validator.swagger.io/validator
  path: /validator
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://oai.swagger.io/api/openapi.json
  path: /api/openapi.json
  method: GET
  query: ''
  tags:
  - api
  type: api
- url: https://generator3.swagger.io/openapi.json
  path: /openapi.json
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://petstore31.swagger.io/api/v31/openapi.json
  path: /api/v31/openapi.json
  method: GET
  query: ''
  tags:
  - api
  type: api
- url: https://petstore3.swagger.io/api/v3/openapi.json
  path: /api/v3/openapi.json
  method: GET
  query: ''
  tags:
  - api
  type: api
- url: http://petstore.swagger.io/v2/swagger.json
  path: /v2/swagger.json
  method: GET
  query: ''
  tags:
  - api
  type: page
- url: https://petstore31.swagger.io/oauth/authorize
  path: /oauth/authorize
  method: GET
  query: ''
  tags:
  - authentication
  type: auth
- url: https://petstore.swagger.io/oauth/authorize
  path: /oauth/authorize
  method: GET
  query: ''
  tags:
  - authentication
  type: auth
- url: https://petstore3.swagger.io/oauth/authorize
  path: /oauth/authorize
  method: GET
  query: ''
  tags:
  - authentication
  type: auth
- url: http://swagger.io/irc/
  path: /irc/
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://swagger.io/terms/
  path: /terms/
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: http://swagger.io/terms/
  path: /terms/
  method: GET
  query: ''
  tags:
  - general
  type: page
auth:
  type: none
