name: test-httpbin
target_url: https://httpbin.org
created_at: '2026-01-12T12:37:48.928809'
endpoints:
- url: https://httpbin.org
  path: ''
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/forms/post
  path: /forms/post
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/spec.json
  path: /spec.json
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/lib/jquery.min.js
  path: /flasgger_static/lib/jquery.min.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/post
  path: /post
  method: POST
  query: ''
  tags:
  - write-operation
  type: page
- url: https://httpbin.org/flasgger_static/oas3/components/request-body.jsx
  path: /flasgger_static/oas3/components/request-body.jsx
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/components/operation-servers.jsx
  path: /flasgger_static/oas3/components/operation-servers.jsx
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/components/operation-link.jsx
  path: /flasgger_static/oas3/components/operation-link.jsx
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/wrap-components/version-stamp.jsx
  path: /flasgger_static/oas3/wrap-components/version-stamp.jsx
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/components/servers.jsx
  path: /flasgger_static/oas3/components/servers.jsx
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/wrap-components/model.jsx
  path: /flasgger_static/oas3/wrap-components/model.jsx
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/wrap-components/auth-item.jsx
  path: /flasgger_static/oas3/wrap-components/auth-item.jsx
  method: GET
  query: ''
  tags:
  - authentication
  type: auth
- url: https://httpbin.org/flasgger_static/oas3/components/callbacks.jsx
  path: /flasgger_static/oas3/components/callbacks.jsx
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/ast/jump-to-path.jsx
  path: /flasgger_static/ast/jump-to-path.jsx
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/view/root-injects.js
  path: /flasgger_static/view/root-injects.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/g
  path: /flasgger_static/g
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/util/index.js
  path: /flasgger_static/util/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/Immutable.js
  path: /flasgger_static/Immutable.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/components/request-body-editor.jsx
  path: /flasgger_static/oas3/components/request-body-editor.jsx
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/view/index.js
  path: /flasgger_static/view/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/components/http-auth.jsx
  path: /flasgger_static/oas3/components/http-auth.jsx
  method: GET
  query: ''
  tags:
  - general
  type: auth
- url: https://httpbin.org/flasgger_static/spec/wrap-actions.js
  path: /flasgger_static/spec/wrap-actions.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/wrap-components/parameters.jsx
  path: /flasgger_static/oas3/wrap-components/parameters.jsx
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/split-pane-mode/components/split-pane-mode.jsx
  path: /flasgger_static/split-pane-mode/components/split-pane-mode.jsx
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/spec/reducers.js
  path: /flasgger_static/spec/reducers.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/spec/index.js
  path: /flasgger_static/spec/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/spec/selectors.js
  path: /flasgger_static/spec/selectors.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/spec/actions.js
  path: /flasgger_static/spec/actions.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/samples/index.js
  path: /flasgger_static/samples/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/samples/fn.js
  path: /flasgger_static/samples/fn.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/wrap-components/markdown.js
  path: /flasgger_static/oas3/wrap-components/markdown.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/wrap-components/index.js
  path: /flasgger_static/oas3/wrap-components/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/spec-extensions/wrap-selectors.js
  path: /flasgger_static/oas3/spec-extensions/wrap-selectors.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/swagger-js/index.js
  path: /flasgger_static/swagger-js/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/split-pane-mode/index.js
  path: /flasgger_static/split-pane-mode/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/reducers.js
  path: /flasgger_static/oas3/reducers.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/components/index.js
  path: /flasgger_static/oas3/components/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/spec-extensions/selectors.js
  path: /flasgger_static/oas3/spec-extensions/selectors.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/helpers.js
  path: /flasgger_static/oas3/helpers.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/actions.js
  path: /flasgger_static/oas3/actions.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/layout/selectors.js
  path: /flasgger_static/layout/selectors.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/logs/index.js
  path: /flasgger_static/logs/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/layout/reducers.js
  path: /flasgger_static/layout/reducers.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/layout/index.js
  path: /flasgger_static/layout/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/err/reducers.js
  path: /flasgger_static/err/reducers.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/err/selectors.js
  path: /flasgger_static/err/selectors.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/selectors.js
  path: /flasgger_static/oas3/selectors.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/filter/opsFilter.js
  path: /flasgger_static/filter/opsFilter.js
  method: GET
  query: ''
  tags:
  - search
  type: page
- url: https://httpbin.org/flasgger_static/oas3/index.js
  path: /flasgger_static/oas3/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/err/error-transformers/transformers/strip-instance.js
  path: /flasgger_static/err/error-transformers/transformers/strip-instance.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/oas3/auth-extensions/wrap-selectors.js
  path: /flasgger_static/oas3/auth-extensions/wrap-selectors.js
  method: GET
  query: ''
  tags:
  - authentication
  type: auth
- url: https://httpbin.org/flasgger_static/on-complete/index.js
  path: /flasgger_static/on-complete/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/err/error-transformers/transformers/parameter-oneof.js
  path: /flasgger_static/err/error-transformers/transformers/parameter-oneof.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/err/error-transformers/transformers/not-of-type.js
  path: /flasgger_static/err/error-transformers/transformers/not-of-type.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/layout/actions.js
  path: /flasgger_static/layout/actions.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/err/error-transformers/hook.js
  path: /flasgger_static/err/error-transformers/hook.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/deep-linking/spec-wrap-actions.js
  path: /flasgger_static/deep-linking/spec-wrap-actions.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/deep-linking/layout-wrap-actions.js
  path: /flasgger_static/deep-linking/layout-wrap-actions.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/err/index.js
  path: /flasgger_static/err/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/deep-linking/helpers.js
  path: /flasgger_static/deep-linking/helpers.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/deep-linking/index.js
  path: /flasgger_static/deep-linking/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/configs/selectors.js
  path: /flasgger_static/configs/selectors.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/filter/index.js
  path: /flasgger_static/filter/index.js
  method: GET
  query: ''
  tags:
  - search
  type: page
- url: https://httpbin.org/flasgger_static/configs/actions.js
  path: /flasgger_static/configs/actions.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/configs/helpers.js
  path: /flasgger_static/configs/helpers.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/auth/spec-wrap-actions.js
  path: /flasgger_static/auth/spec-wrap-actions.js
  method: GET
  query: ''
  tags:
  - authentication
  type: auth
- url: https://httpbin.org/flasgger_static/oas3/wrap-components/online-validator-badge.js
  path: /flasgger_static/oas3/wrap-components/online-validator-badge.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/err/actions.js
  path: /flasgger_static/err/actions.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/configs/index.js
  path: /flasgger_static/configs/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/auth/index.js
  path: /flasgger_static/auth/index.js
  method: GET
  query: ''
  tags:
  - authentication
  type: auth
- url: https://httpbin.org/flasgger_static/auth/actions.js
  path: /flasgger_static/auth/actions.js
  method: GET
  query: ''
  tags:
  - authentication
  type: auth
- url: https://httpbin.org/flasgger_static/ast/index.js
  path: /flasgger_static/ast/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/ast/ast.js
  path: /flasgger_static/ast/ast.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/auth/selectors.js
  path: /flasgger_static/auth/selectors.js
  method: GET
  query: ''
  tags:
  - authentication
  type: auth
- url: https://httpbin.org/flasgger_static/all.js
  path: /flasgger_static/all.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/Autolinker.js
  path: /flasgger_static/Autolinker.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/index.js
  path: /flasgger_static/index.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/download-url.js
  path: /flasgger_static/download-url.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/e.json%7C%7Cu.call%28n,i%29%7C%7C%21u.call%28t,i%29%7C%7C%28e.line=a%7C%7Ce.line,e.position=s%7C%7Ce.position,P%28e,
  path: /flasgger_static/e.json%7C%7Cu.call%28n,i%29%7C%7C%21u.call%28t,i%29%7C%7C%28e.line=a%7C%7Ce.line,e.position=s%7C%7Ce.position,P%28e,
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/t.json%7C%7Cu.call%28n,i%29%7C%7C%21u.call%28e,i%29%7C%7C%28t.line=s%7C%7Ct.line,t.position=a%7C%7Ct.position,O%28t,
  path: /flasgger_static/t.json%7C%7Cu.call%28n,i%29%7C%7C%21u.call%28e,i%29%7C%7C%28t.line=s%7C%7Ct.line,t.position=a%7C%7Ct.position,O%28t,
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/configs/reducers.js
  path: /flasgger_static/configs/reducers.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/configs/spec-actions.js
  path: /flasgger_static/configs/spec-actions.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/swagger-ui-standalone-preset.js
  path: /flasgger_static/swagger-ui-standalone-preset.js
  method: GET
  query: ''
  tags:
  - general
  type: page
- url: https://httpbin.org/flasgger_static/3200/oauth2-redirect.html
  path: /flasgger_static/3200/oauth2-redirect.html
  method: GET
  query: ''
  tags:
  - resource-id
  type: auth
- url: https://httpbin.org/flasgger_static/auth/reducers.js
  path: /flasgger_static/auth/reducers.js
  method: GET
  query: ''
  tags:
  - authentication
  type: auth
- url: https://httpbin.org/flasgger_static/swagger-ui-bundle.js
  path: /flasgger_static/swagger-ui-bundle.js
  method: GET
  query: ''
  tags:
  - general
  type: page
auth:
  type: none
