name: test-new
target_url: https://example.com
created_at: '2026-01-12T22:41:35.716274'
endpoints:
- url: https://example.com
  path: ''
  method: GET
  query: ''
  tags:
  - general
  type: page
auth:
  type: none
